site_name: Wikipedia

repo_name: "Wikipedia"
repo_url: "https://github.com/Interacao-Humano-Computador/2023.1-Wikipedia"

copyright: "Copyright &copy; 2023 Wikipedia"

theme:
  name: material
  language: pt-BR
  favicon: images/wikipedia.png

  palette:
    - scheme: default
      primary: grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Trocar para o modo escuro

    - scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Trocar para o modo claro

  icon:
    repo: fontawesome/brands/github

  logo: images/wikipedia.png

plugins:
  - search
  - charts

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite

nav:
  - Home: index.md
  - Atas:
      - 01/04/2023: atas/ata_01_04.md
      - 07/04/2023: atas/ata_07_04.md
      - 21/04/2023: atas/ata_21_04.md
      - 05/05/2023: atas/ata_05_05.md
      - 19/05/2023: atas/ata_19_05.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentacao 4: apresentacoes/apresentacao4.md
      - Apresentacao 5: apresentacoes/apresentacao5.md
      - Apresentacao 6: apresentacoes/apresentacao6.md
      - Apresentacao 7: apresentacoes/apresentacao7.md
      - Apresentacao 8: apresentacoes/apresentacao8.md
      - Apresentacao 9: apresentacoes/apresentacao9.md
      - Apresentacao 10: apresentacoes/apresentacao10.md
  - Politicas:
      - Metodologias: politicas/metodologias.md
      - Issues: politicas/issues.md
      - Pull requests: politicas/pullrequest.md
      - Commit: politicas/commit.md
      - Branch: politicas/branch.md
  - Planejamento:
      - Cronogramas:
          - Planejado: planejamento/cronogramaPlanejado.md
          - Realizado: planejamento/cronogramaRealizado.md
      - Sites analisados: planejamento/sitesAnalisados.md
      - Site selecionado:
          - Sobre a Wikipedia: planejamento/siteEscolhido.md
          - Avaliação Heurística: planejamento/avaliacaoHeuristica.md
      - Ferramentas: planejamento/ferramentas.md
      - Disponibildade dos Membros: planejamento/disponibilidade.md
      - Processo de Design: planejamento/processo.md
  - Análise de Requisitos:
      - Perfil de Usuário: analise-de-requisitos/perfilDeUsuario.md
      - Personas: analise-de-requisitos/personas.md
      - Aspectos éticos: analise-de-requisitos/aspectosEticos.md
      - Análise de Tarefas:
          - AHT: analise-de-requisitos/aht.md
          - GOMS: analise-de-requisitos/goms.md
      - Princípios Gerais do Projeto: analise-de-requisitos/principiosGerais.md
      - Características da Plataforma: analise-de-requisitos/caracteristicaDaPlataforma.md
      - Guia de estilo: analise-de-requisitos/guiaDeEstilo.md
      - Metas de Usabilidade: analise-de-requisitos/metasUsabilidade.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Storyboard:
              - Planejamento da avaliação: design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoDaAvaliacao.md
              - Planejamento do relato: design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoResultadosAvaliacaoStoryboard.md
              - Relato dos resultados: design-avaliacao-desenvolvimento/nivel1/storyboard/relatoDosResultadosStoryBoard.md
          - Análise de tarefas:
              - Planejamento da avaliação: design-avaliacao-desenvolvimento/nivel1/analiseDeTarefas/planejamentoDaAvaliacaoTarefas.md
              - Planejamento do relato: design-avaliacao-desenvolvimento/nivel1/analiseDeTarefas/planejamentoResultadosAnalisesTarefas.md
              - Relato dos resultados: design-avaliacao-desenvolvimento/nivel1/analiseDeTarefas/relatoDaAnaliseDeTarefa.md
      - Nível 2:
          - Protótipo de papel:
              - Planejamento da Avaliação: design-avaliacao-desenvolvimento/nivel2/prototipoDePapel/planejamentoDaAvaliacaoPrototipoDePapel.md
              - Planejamento do relato: design-avaliacao-desenvolvimento/nivel2/prototipoDePapel/planejamentoRelatoResultadosAvaliacaoPrototipoPapel.md
              - Relato dos resultados: design-avaliacao-desenvolvimento/nivel2/prototipoDePapel/relatoDosResultados.md
          - Protótipos realizados: design-avaliacao-desenvolvimento/nivel2/prototipoDePapel/prototipos.md
      - Nível 3:
          - Protótipo de Alta Fidelidade:
              - Planejamento da Avaliação: design-avaliacao-desenvolvimento/nivel3/prototipoAltaFidelidade/planejamentoAvaliacaoPrototipoAltaFidelidade.md
              - Planejamento do relato: design-avaliacao-desenvolvimento/nivel3/planejamentoRelatoResultadosAvaliacaoPrototipoDeAltaFidelidade.md
              - Relato dos resultados: design-avaliacao-desenvolvimento/nivel3/prototipoAltaFidelidade/relatoPrototipoAltaFidelidade.md
  - Verificação do grupo 3:
      - Planejamento da Verificação: verificacao/planejamento.md
      - Ponto de Controle 1:
          - Cronograma: verificacao/pontoControle1/cronograma.md
          - Ferramentas: verificacao/pontoControle1/ferramentas.md
          - Metodologias: verificacao/pontoControle1/metodologia.md
          - Processos de Design: verificacao/pontoControle1/processosDeDesign.md
          - Site Selecionado: verificacao/pontoControle1/siteEscolhido.md
          - Sites avaliados: verificacao/pontoControle1/sitesAvaliados.md
      - Ponto de Controle 2:
          - Aspectos éticos: verificacao/pontoControle2/aspectosEticos.md
          - Análise das Tarefas do Usuário: verificacao/pontoControle2/analiseDasTarefas.md
          - Perfil do Usuário: verificacao/pontoControle2/perfilUsuario.md
          - Criação dos cenários: verificacao/pontoControle2/cenarios.md
          - Personas: verificacao/pontoControle2/personas.md
      - Ponto de Controle 3:
          - Metas de Usabilidade: verificacao/pontoControle3/metasUsabilidade.md
          - Definir os princípios gerais do projeto: verificacao/pontoControle3/principiosGerais.md
          - Guia de Estilo: verificacao/pontoControle3/guiaDeEstilo.md
          - Características da Plataforma: verificacao/pontoControle3/caracteristicasDaPlataforma.md
      - Ponto de Controle 4:
          - Planejar a avaliação do Story Board: verificacao/pontoControle4/planejamentoAvaliacaoStoryBoard.md
          - Planejamento do relato da Avaliação do Storyboard: verificacao/pontoControle4/planejamentoRelatoDaAvaliaçãoDoStoryBoard.md
          - Planejar a avaliação da Análise de Tarefas: verificacao/pontoControle4/planejamentoAvaliacaoAnaliseDeTarefas.md
          - Planejamento dos Resultados das Análises de Tarefas: verificacao/pontoControle4/relatoDaAnaliseDeTarefa.md
      - Ponto de Controle 5:
          - Relato da análise de tarefa: verificacao/pontoControle5/relatoAnaliseTarefa.md
          - Relato do Story Board: verificacao/pontoControle5/relatoStoryboard.md
          - Planejamento do Relato dos Resultados: verificacao/pontoControle5/planejamentoRelatoDosResultados.md
          - Planejamento da avaliação do protótipo de papel: verificacao/pontoControle5/planejamentoPrototipoDePapel.md
  - Verificação:
    - Planejamento: verificacao2/planejamento.md
    - Ponto de Controle 1:
          - Cronograma: verificacao2/pontoControle1/cronograma.md
          - Ferramentas: verificacao2/pontoControle1/ferramentas.md
          - Metodologias: verificacao2/pontoControle1/metodologia.md
          - Processos de Design: verificacao2/pontoControle1/processosDeDesign.md
          - Site Selecionado: verificacao2/pontoControle1/siteEscolhido.md
          - Sites avaliados: verificacao2/pontoControle1/sitesAvaliados.md
    - Ponto de Controle 2:
          - Aspectos éticos: verificacao2/pontoControle2/aspectosEticos.md
          - Análise das Tarefas do Usuário: verificacao2/pontoControle2/analiseDasTarefas.md
          - Perfil do Usuário: verificacao2/pontoControle2/perfilUsuario.md
          - Personas: verificacao2/pontoControle2/personas.md
    - Ponto de Controle 3:
          - Metas de Usabilidade: verificacao2/pontoControle3/metasUsabilidade.md
          - Definir os princípios gerais do projeto: verificacao2/pontoControle3/principiosGerais.md
          - Guia de Estilo: verificacao2/pontoControle3/guiaDeEstilo.md
          - Características da Plataforma: verificacao2/pontoControle3/caracteristicasDaPlataforma.md
    - Ponto de Controle 4:
          - Planejar a avaliação do Story Board: verificacao2/pontoControle4/planejamentoAvaliacaoStoryBoard.md
          - Planejamento do relato da Avaliação do Storyboard: verificacao2/pontoControle4/planejamentoRelatoDaAvaliaçãoDoStoryBoard.md
          - Planejar a avaliação da Análise de Tarefas: verificacao2/pontoControle4/planejamentoAvaliacaoAnaliseDeTarefas.md
          - Planejamento do Relato dos Resultados das Análises de Tarefas: verificacao2/pontoControle4/planejamentoRelatoDaAnaliseDeTarefas.md
    - Ponto de Controle 5:
          - Relato da análise de tarefa: verificacao2/pontoControle5/relatoAnaliseTarefa.md
          - Relato do Story Board: verificacao2/pontoControle5/relatoStoryboard.md
          - Planejamento do Relato dos Resultados: verificacao2/pontoControle5/planejamentoRelatoDosResultados.md
          - Planejamento da avaliação do protótipo de papel: verificacao2/pontoControle5/planejamentoPrototipoDePapel.md
    - Ponto de Controle 7:
          - Relato do prótipo de papel: verificacao2/pontoControle7/relatoPrototipoDePapel.md
          - Planejamento da avaliação do protótipo de alta fidelidade: verificacao2/pontoControle7/planejamentoAvaliacaoPrototipoDeAltaFidelidade.md
          - Planejamento do relato dos resultados do protótipo de alta fidelidade: verificacao2/pontoControle7/planejamentoRelatoPrototipoDeAltaFidelidade.md
  - Entrega Final: entregaFinal/entregaFinal.md
